all:gcd get isly pro 
gcd:Gcd.c
	gcc Gcd.c -o gcd 
get:Getdata.c
	gcc Getdata.c -o get 
isly:Isly.c 
	gcc Isly.c -o isly 
pro:process.c
	gcc process.c -o pro 

.PHONY:clean
clean:
	rm gcd get isly pro 
